// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetBattleResolveEncryptionSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetBattleResolveEncryptionSystem {
  function resolveBattleEncryption(bytes32 battleId, bytes32 aggressorEntity, bytes32 targetEntity) external;
}
