// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetBattleResolveRaidSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetBattleResolveRaidSystem {
  function resolveBattleRaid(bytes32 battleId, bytes32 raider, bytes32 target) external;
}
