// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetBattleApplyDamageSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetBattleApplyDamageSystem {
  function applyDamageToWithAllies(bytes32 battleId, bytes32 entity, uint256 damage) external;
}
