// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IStore } from "@latticexyz/store/src/IStore.sol";
import { createPrototype } from "../../libraries/prototypes/createPrototype.sol";
import { ERock, EBuilding, EResource } from "../Types.sol";
import { P_Asteroid, P_AsteroidTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId, P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId } from "../Tables.sol";

bytes32 constant prototypeId = "World";
bytes32 constant WorldPrototypeId = prototypeId;
uint256 constant LENGTH = 1;

function WorldKeys() pure returns (bytes32[] memory) {
  bytes32[] memory _keyTuple = new bytes32[](0);

  return _keyTuple;
}

function WorldLevelKeys(uint32 level) pure returns (bytes32[] memory) {
  bytes32[] memory _keyTuple = new bytes32[](1);
  _keyTuple[0] = bytes32(uint256(level));

  return _keyTuple;
}

function WorldPrototype(IStore store) {
  bytes32[] memory keys = WorldKeys();
  bytes32[] memory tableIds = new bytes32[](LENGTH);
  bytes[] memory values = new bytes[](LENGTH);

  tableIds[0] = P_AsteroidTableId;

  values[0] = P_Asteroid.encode(37, 25);

  createPrototype(store, keys, tableIds, values);

  bytes32[] memory levelKeys;

  /* ----------------------------- LEVEL 0 ----------------------------- */
  levelKeys = WorldLevelKeys(0);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x4e554c4c00000000000000000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 1 ----------------------------- */
  levelKeys = WorldLevelKeys(1);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x4d61696e42617365000000000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 2 ----------------------------- */
  levelKeys = WorldLevelKeys(2);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x4c69746869756d4d696e65000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 3 ----------------------------- */
  levelKeys = WorldLevelKeys(3);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x49726f6e4d696e65000000000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 4 ----------------------------- */
  levelKeys = WorldLevelKeys(4);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x436f707065724d696e6500000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 5 ----------------------------- */
  levelKeys = WorldLevelKeys(5);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x53756c6675724d696e6500000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 6 ----------------------------- */
  levelKeys = WorldLevelKeys(6);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x49726f6e506c617465466163746f727900000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 7 ----------------------------- */
  levelKeys = WorldLevelKeys(7);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x416c6c6f79466163746f72790000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 8 ----------------------------- */
  levelKeys = WorldLevelKeys(8);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x505643656c6c466163746f727900000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 9 ----------------------------- */
  levelKeys = WorldLevelKeys(9);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x526f636b65744675656c466163746f7279000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 10 ----------------------------- */
  levelKeys = WorldLevelKeys(10);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x536f6c617250616e656c00000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 11 ----------------------------- */
  levelKeys = WorldLevelKeys(11);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x48616e6761720000000000000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 12 ----------------------------- */
  levelKeys = WorldLevelKeys(12);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x556e6974547261696e696e674275696c64696e67000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 13 ----------------------------- */
  levelKeys = WorldLevelKeys(13);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x53746f72616765556e6974000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 14 ----------------------------- */
  levelKeys = WorldLevelKeys(14);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x44726f6e65466163746f72790000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 15 ----------------------------- */
  levelKeys = WorldLevelKeys(15);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x537461726d617070657200000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);

  /* ----------------------------- LEVEL 16 ----------------------------- */
  levelKeys = WorldLevelKeys(16);
  tableIds = new bytes32[](1);
  values = new bytes[](1);

  tableIds[0] = P_BuildingTypeToPrototypeTableId;

  values[0] = P_BuildingTypeToPrototype.encode(0x4c454e4754480000000000000000000000000000000000000000000000000000);

  createPrototype(store, levelKeys, tableIds, values);
}
