import { Animation } from "@latticexyz/phaserx/dist/types";

const animationConfig: Animation<any>[] = [
  {
    key: "mainbase",
    assetKey: "sprite-atlas",
    frameRate: 30,
    startFrame: 0,
    endFrame: 169,
    repeat: -1,
    prefix: "mainbase/mainbase-",
    suffix: ".png",
  },
  {
    key: "node",
    assetKey: "sprite-atlas",
    frameRate: 13,
    startFrame: 0,
    endFrame: 49,
    repeat: -1,
    prefix: "node/node-",
    suffix: ".png",
  },
  {
    key: "advancedbatteryfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "advancedbatteryfactory/advancedbatteryfactory-",
    suffix: ".png",
  },
  {
    key: "basicbatteryfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 17,
    repeat: -1,
    prefix: "basicbatteryfactory/basicbatteryfactory-",
    suffix: ".png",
  },
  {
    key: "densemetalrefinery",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 39,
    repeat: -1,
    prefix: "densemetalrefinery/densemetalrefinery-",
    suffix: ".png",
  },
  {
    key: "hardeneddrill",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "hardeneddrill/hardeneddrill-",
    suffix: ".png",
  },
  {
    key: "hightempfoundry",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 39,
    repeat: -1,
    prefix: "hightempfoundry/hightempfoundry-",
    suffix: ".png",
  },
  {
    key: "iridiumdrillbitfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 15,
    repeat: -1,
    prefix: "iridiumdrillbitfactory/iridiumdrillbitfactory-",
    suffix: ".png",
  },
  {
    key: "kimberlitecatalyst",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 15,
    repeat: -1,
    prefix: "kimberlitecatalyst/kimberlitecatalyst-",
    suffix: ".png",
  },
  {
    key: "laserfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 13,
    repeat: -1,
    prefix: "laserfactory/laserfactory-",
    suffix: ".png",
  },
  {
    key: "minerdrill",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "minerdrill/minerdrill-",
    suffix: ".png",
  },
  {
    key: "missilelaunchcomplex",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 7,
    repeat: -1,
    prefix: "missilelaunchcomplex/missilelaunchcomplex-",
    suffix: ".png",
  },
  {
    key: "platingfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 10,
    repeat: -1,
    prefix: "platingfactory/platingfactory-",
    suffix: ".png",
  },
  {
    key: "precisionmachineryfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 9,
    repeat: -1,
    prefix: "precisionmachineryfactory/precisionmachineryfactory-",
    suffix: ".png",
  },
  {
    key: "precisionpneumaticdrill",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 59,
    repeat: -1,
    prefix: "precisionpneumaticdrill/precisionpneumaticdrill-",
    suffix: ".png",
  },
];

export default animationConfig;
