import { Animation } from "@latticexyz/phaserx/dist/types";

export const animationConfig: Animation<any>[] = [
  {
    key: "mainbase/level1",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 0,
    repeat: -1,
    prefix: "sprites/mainbase/level1/bigmainbase-level1-",
    suffix: ".png",
  },
  {
    key: "mainbase/level2",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 0,
    repeat: -1,
    prefix: "sprites/mainbase/level1/bigmainbase-level2-",
    suffix: ".png",
  },
  {
    key: "mainbase/level3",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 0,
    repeat: -1,
    prefix: "sprites/mainbase/level1/bigmainbase-level3-",
    suffix: ".png",
  },
  {
    key: "mainbase/level4",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 0,
    repeat: -1,
    prefix: "sprites/mainbase/level1/bigmainbase-level4-",
    suffix: ".png",
  },
  {
    key: "mainbase/level5",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 0,
    repeat: -1,
    prefix: "sprites/mainbase/level1/bigmainbase-level5-",
    suffix: ".png",
  },
  {
    key: "ironmine/level1",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 4,
    endFrame: 0,
    repeat: -1,
    prefix: "sprites/ironmine/level1/iron-miner-",
  },
  {
    key: "ironmine/level2",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/ironmine/level2/iron-miner-level2-",
  },
  {
    key: "ironmine/level3",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/ironmine/level3/iron-miner-level3-",
  },
  {
    key: "coppermine/level1",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/coppermine/level1/copper-miner-",
  },
  {
    key: "coppermine/level2",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/coppermine/level2/copper-miner-level2-",
  },
  {
    key: "coppermine/level3",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/coppermine/level3/copper-miner-level3-",
  },
  {
    key: "lithiummine/level1",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/lithiummine/level1/lithium-miner-",
  },
  {
    key: "lithiummine/level2",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/lithiummine/level2/lithium-miner-level2-",
  },
  {
    key: "lithiummine/level3",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 4,
    repeat: -1,
    prefix: "sprites/lithiummine/level3/lithium-miner-level3-",
  },
  {
    key: "alloyfactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 19,
    repeat: -1,
    prefix: "sprites/alloyfactory/level1/alloyfactory-level1-",
  },
  {
    key: "alloyfactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 19,
    repeat: -1,
    prefix: "sprites/alloyfactory/level2/alloyfactory-level2-",
  },
  {
    key: "ironplatefactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/ironplatefactory/level1/ironplatefactory-level1-",
  },
  {
    key: "ironplatefactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/ironplatefactory/level2/ironplatefactory-level2-",
  },
  {
    key: "node",
    assetKey: "sprite-atlas",
    frameRate: 13,
    startFrame: 0,
    endFrame: 49,
    repeat: -1,
    prefix: "sprites/node/node-",
    suffix: ".png",
  },
  {
    key: "advancedbatteryfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/advancedbatteryfactory/advancedbatteryfactory-",
    suffix: ".png",
  },
  {
    key: "basicbatteryfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 17,
    repeat: -1,
    prefix: "sprites/basicbatteryfactory/basicbatteryfactory-",
    suffix: ".png",
  },
  {
    key: "densemetalrefinery",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 39,
    repeat: -1,
    prefix: "sprites/densemetalrefinery/densemetalrefinery-",
    suffix: ".png",
  },
  {
    key: "hardeneddrill",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/hardeneddrill/hardeneddrill-",
    suffix: ".png",
  },
  {
    key: "hightempfoundry",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 39,
    repeat: -1,
    prefix: "sprites/hightempfoundry/hightempfoundry-",
    suffix: ".png",
  },
  {
    key: "iridiumdrillbitfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/iridiumdrillbitfactory/iridiumdrillbitfactory-",
    suffix: ".png",
  },
  {
    key: "kimberlitecatalyst",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/kimberlitecatalyst/kimberlitecatalyst-",
    suffix: ".png",
  },
  {
    key: "laserfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 13,
    repeat: -1,
    prefix: "sprites/laserfactory/laserfactory-",
    suffix: ".png",
  },
  {
    key: "minerdrill",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/minerdrill/minerdrill-",
    suffix: ".png",
  },
  {
    key: "missilelaunchcomplex",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/missilelaunchcomplex/missilelaunchcomplex-",
    suffix: ".png",
  },
  {
    key: "platingfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/platingfactory/platingfactory-",
    suffix: ".png",
  },
  {
    key: "precisionmachineryfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/precisionmachineryfactory/precisionmachineryfactory-",
    suffix: ".png",
  },
  {
    key: "precisionpneumaticdrill",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 59,
    repeat: -1,
    prefix: "sprites/precisionpneumaticdrill/precisionpneumaticdrill-",
    suffix: ".png",
  },
  {
    key: "dronefactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/dronefactory/dronefactory-",
  },
];
