import { Animation } from "@latticexyz/phaserx/dist/types";

export const animationConfig: Animation<any>[] = [
  {
    key: "mainbase",
    assetKey: "sprite-atlas",
    frameRate: 30,
    startFrame: 0,
    endFrame: 169,
    repeat: -1,
    prefix: "sprites/mainbase/mainbase-",
    suffix: ".png",
  },
  {
    key: "node",
    assetKey: "sprite-atlas",
    frameRate: 13,
    startFrame: 0,
    endFrame: 49,
    repeat: -1,
    prefix: "sprites/node/node-",
    suffix: ".png",
  },
  {
    key: "advancedbatteryfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/advancedbatteryfactory/advancedbatteryfactory-",
    suffix: ".png",
  },
  {
    key: "basicbatteryfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 17,
    repeat: -1,
    prefix: "sprites/basicbatteryfactory/basicbatteryfactory-",
    suffix: ".png",
  },
  {
    key: "densemetalrefinery",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 39,
    repeat: -1,
    prefix: "sprites/densemetalrefinery/densemetalrefinery-",
    suffix: ".png",
  },
  {
    key: "hardeneddrill",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/hardeneddrill/hardeneddrill-",
    suffix: ".png",
  },
  {
    key: "hightempfoundry",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 39,
    repeat: -1,
    prefix: "sprites/hightempfoundry/hightempfoundry-",
    suffix: ".png",
  },
  {
    key: "iridiumdrillbitfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/iridiumdrillbitfactory/iridiumdrillbitfactory-",
    suffix: ".png",
  },
  {
    key: "kimberlitecatalyst",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/kimberlitecatalyst/kimberlitecatalyst-",
    suffix: ".png",
  },
  {
    key: "laserfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 13,
    repeat: -1,
    prefix: "sprites/laserfactory/laserfactory-",
    suffix: ".png",
  },
  {
    key: "minerdrill",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 3,
    repeat: -1,
    prefix: "sprites/minerdrill/minerdrill-",
    suffix: ".png",
  },
  {
    key: "missilelaunchcomplex",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/missilelaunchcomplex/missilelaunchcomplex-",
    suffix: ".png",
  },
  {
    key: "platingfactory",
    assetKey: "sprite-atlas",
    frameRate: 4,
    startFrame: 0,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/platingfactory/platingfactory-",
    suffix: ".png",
  },
  {
    key: "precisionmachineryfactory",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/precisionmachineryfactory/precisionmachineryfactory-",
    suffix: ".png",
  },
  {
    key: "precisionpneumaticdrill",
    assetKey: "sprite-atlas",
    frameRate: 1,
    startFrame: 0,
    endFrame: 59,
    repeat: -1,
    prefix: "sprites/precisionpneumaticdrill/precisionpneumaticdrill-",
    suffix: ".png",
  },
];
