// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum EBuilding {
  NULL,
  MainBase,
  WormholeBase,
  LithiumMine,
  IronMine,
  CopperMine,
  KimberliteMine,
  IridiumMine,
  TitaniumMine,
  PlatinumMine,
  IronPlateFactory,
  AlloyFactory,
  PVCellFactory,
  SolarPanel,
  Hangar,
  Garage,
  StorageUnit,
  Workshop,
  DroneFactory,
  Starmapper,
  SAM,
  ShieldGenerator,
  Vault,
  Market,
  Shipyard,
  LENGTH
}

enum EResource {
  NULL,
  Iron,
  Copper,
  Lithium,
  Titanium,
  Iridium,
  Kimberlite,
  Platinum,
  IronPlate,
  Alloy,
  PVCell,
  U_Electricity,
  U_Housing,
  U_MaxFleets,
  U_Defense,
  U_Unraidable,
  U_AdvancedUnraidable,
  R_HP,
  R_Encryption,
  M_DefenseMultiplier,
  LENGTH
}

enum EUnit {
  NULL,
  AegisDrone,
  AnvilDrone,
  StingerDrone,
  HammerDrone,
  MinutemanMarine,
  TridentMarine,
  LightningCraft,
  ColonyShip,
  Droid,
  LENGTH
}

enum EMap {
  NULL,
  Primary,
  Kimberlite,
  Iridium,
  Platinum,
  Titanium,
  Wormhole,
  Common,
  LENGTH
}

enum EObjectives {
  NULL,
  JoinDiscord,
  FollowTwitter,
  BuildIronMine,
  BuildCopperMine,
  BuildLithiumMine,
  UpgradeMainBase2,
  UpgradeMainBase3,
  UpgradeMainBase4,
  UpgradeMainBase5,
  ExpandBase2,
  ExpandBase3,
  ExpandBase4,
  UpgradeIronMine2,
  UpgradeIronMine3,
  UpgradeCopperMine2,
  UpgradeCopperMine3,
  UpgradeLithiumMine2,
  UpgradeLithiumMine3,
  BuildGarage,
  UpgradeGarage,
  BuildWorkshop,
  UpgradeWorkshop,
  CreateFleet,
  TransferFromAsteroid,
  TransferFromFleet,
  SendFleet,
  BattleAsteroid,
  OpenBattleReport,
  BattleFleet,
  BuildShipyard,
  TrainColonyShip,
  DecryptAttack,
  CaptureAsteroid,
  CaptureMotherlodeAsteroid,
  BuildRareMine,
  EarnPrimodiumOnAsteroid,
  CaptureVolatileShard,
  ExplodeVolatileShard,
  CaptureWormholeAsteroid,
  TeleportResources,
  BuildStarmapper,
  CreateFleet2,
  DefendWithFleet,
  BlockWithFleet,
  LandFleet,
  TrainMinutemanMarine,
  TrainTridentMarine,
  TrainLightningCraft,
  UpgradeUnit,
  BuildDroneFactory,
  TrainAnvilDrone,
  TrainHammerDrone,
  TrainAegisDrone,
  TrainStingerDrone,
  BuildHangar,
  BuildShieldGenerator,
  BuildVault,
  BuildSAMLauncher,
  BuildStorageUnit,
  UpgradeStorageUnit2,
  BuildIronPlateFactory,
  BuildAlloyFactory,
  BuildPVCellFactory,
  BuildSolarPanel,
  UpgradeSolarPanel2,
  BuildMarket,
  MarketSwap,
  JoinAlliance,
  PrimoPlayer,
  LENGTH
}

enum EAllianceInviteMode {
  NULL,
  Open,
  Closed,
  LENGTH
}

enum EAllianceRole {
  NULL,
  Owner,
  CanGrantRole,
  CanKick,
  CanInvite,
  Member,
  LENGTH
}

enum EFleetStance {
  NULL,
  Follow,
  Defend,
  Block,
  LENGTH
}

enum EPointType {
  NULL,
  Shard,
  Wormhole,
  LENGTH
}
