// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;
import { VoxelCoord } from "std-contracts/components/VoxelCoordComponent.sol";
import { Coord } from "std-contracts/components/CoordComponent.sol";

struct ResourceCost {
  uint256 resource;
  uint32 cost;
}

struct BuildingPrototype {
  uint32 maxLevel;
  uint256 requiredTile; // tile building must be built on
  uint256 passiveResource; // resource generated by building passively
  uint32 passiveRate;
  uint32[] productionRates; // per level
  int32[] blueprint;
  uint256[] requiredResearch; // research required to unlock each level
  uint256[] requiredPassiveResources; // passive resources required to unlock each level
  uint32[] requiredPassiveCounts; // passive resource amounts required to unlock each level
  ResourceCost[][] requiredResources; // resources require to unlock each level
}
