// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { WorldPrototype, WorldPrototypeId } from "./prototypes/WorldPrototype.sol";
import { ExpansionPrototype, ExpansionPrototypeId } from "./prototypes/ExpansionPrototype.sol";
import { MainBasePrototype, MainBasePrototypeId } from "./prototypes/MainBasePrototype.sol";
import { IronMinePrototype, IronMinePrototypeId } from "./prototypes/IronMinePrototype.sol";
