// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Prototype, PrototypeId } from "./prototypes/Prototype.sol";
import { MainBasePrototype, MainBasePrototypeId } from "./prototypes/MainBasePrototype.sol";
