// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { ReversePosition, ReversePositionTableId } from "./tables/ReversePosition.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Level, LevelTableId } from "./tables/Level.sol";
import { LastClaimedAt, LastClaimedAtTableId } from "./tables/LastClaimedAt.sol";
import { HomeAsteroid, HomeAsteroidTableId } from "./tables/HomeAsteroid.sol";
import { P_Asteroid, P_AsteroidData, P_AsteroidTableId } from "./tables/P_Asteroid.sol";
import { AsteroidCount, AsteroidCountTableId } from "./tables/AsteroidCount.sol";
import { RockType, RockTypeTableId } from "./tables/RockType.sol";
import { Dimensions, DimensionsData, DimensionsTableId } from "./tables/Dimensions.sol";
import { Spawned, SpawnedTableId } from "./tables/Spawned.sol";
import { P_Terrain, P_TerrainTableId } from "./tables/P_Terrain.sol";
import { P_BuildingTypeToPrototype, P_BuildingTypeToPrototypeTableId } from "./tables/P_BuildingTypeToPrototype.sol";
import { P_Blueprint, P_BlueprintTableId } from "./tables/P_Blueprint.sol";
import { P_MaxLevel, P_MaxLevelTableId } from "./tables/P_MaxLevel.sol";
import { BuildingType, BuildingTypeTableId } from "./tables/BuildingType.sol";
import { Children, ChildrenTableId } from "./tables/Children.sol";
