// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { ReversePosition, ReversePositionTableId } from "./tables/ReversePosition.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Level, LevelTableId } from "./tables/Level.sol";
import { LastClaimedAt, LastClaimedAtTableId } from "./tables/LastClaimedAt.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { AsteroidCount, AsteroidCountTableId } from "./tables/AsteroidCount.sol";
import { RockType, RockTypeTableId } from "./tables/RockType.sol";
import { P_Blueprint, P_BlueprintTableId } from "./tables/P_Blueprint.sol";
import { P_MaxLevel, P_MaxLevelTableId } from "./tables/P_MaxLevel.sol";
import { P_RequiredTile, P_RequiredTileTableId } from "./tables/P_RequiredTile.sol";
import { BuildingType, BuildingTypeTableId } from "./tables/BuildingType.sol";
import { Children, ChildrenTableId } from "./tables/Children.sol";
