// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ERock {
  NULL,
  Asteroid,
  Motherlode,
  LENGTH
}

enum EBuilding {
  NULL,
  MainBase,
  LithiumMine,
  IronMine,
  CopperMine,
  SulfurMine,
  IronPlateFactory,
  AlloyFactory,
  PVCellFactory,
  RocketFuelFactory,
  SolarPanel,
  Hangar,
  UnitTrainingBuilding,
  StorageUnit,
  DroneFactory,
  Starmapper,
  LENGTH
}

enum EResource {
  NULL,
  Sandstone,
  Biofilm,
  Alluvium,
  Regolith,
  Bedrock,
  Water,
  Lithium,
  Iron,
  Copper,
  Sulfur,
  Titanium,
  Iridium,
  Osmium,
  Tungsten,
  Kimberlite,
  Platinum,
  Uraninite,
  Bolutite,
  MoveCount,
  U_Electricity,
  U_Housing,
  U_Vessel,
  LENGTH
}
