// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ERock {
  NULL,
  Asteroid,
  Motherlode,
  LENGTH
}

enum EBuilding {
  NULL,
  MainBase,
  StarMapper,
  StorageUnit,
  DroneFactory,
  LithiumMine,
  IronMine,
  CopperMine,
  TitaniumMine,
  IridiumMine,
  OsmiumMine,
  TungstenMine,
  KimberliteMine,
  UraniniteMine,
  BolutiteMine,
  SulfurMine,
  IronPlateFactory,
  AlloyFactory,
  PVCellFactory,
  RocketFuelFactory,
  SolarPanel,
  Hangar,
  LENGTH
}
