// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Messages, MessagesTableId } from "./tables/Messages.sol";
import { UpgradeBounty, UpgradeBountyTableId } from "./tables/UpgradeBounty.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
