// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Messages, MessagesTableId } from "./tables/Messages.sol";
import { UpgradeBounty, UpgradeBountyTableId } from "./tables/UpgradeBounty.sol";
import { Home, HomeTableId } from "./tables/Home.sol";
import { P_GameConfig, P_GameConfigData, P_GameConfigTableId } from "./tables/P_GameConfig.sol";
import { P_ColonyShipConfig, P_ColonyShipConfigData, P_ColonyShipConfigTableId } from "./tables/P_ColonyShipConfig.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { ReversePosition, ReversePositionTableId } from "./tables/ReversePosition.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Level, LevelTableId } from "./tables/Level.sol";
import { Spawned, SpawnedTableId } from "./tables/Spawned.sol";
import { P_RequiredTile, P_RequiredTileTableId } from "./tables/P_RequiredTile.sol";
import { P_RequiredBaseLevel, P_RequiredBaseLevelTableId } from "./tables/P_RequiredBaseLevel.sol";
import { P_RequiredResources, P_RequiredResourcesData, P_RequiredResourcesTableId } from "./tables/P_RequiredResources.sol";
import { P_RequiredDependency, P_RequiredDependencyData, P_RequiredDependencyTableId } from "./tables/P_RequiredDependency.sol";
import { P_RequiredUpgradeResources, P_RequiredUpgradeResourcesData, P_RequiredUpgradeResourcesTableId } from "./tables/P_RequiredUpgradeResources.sol";
import { P_Blueprint, P_BlueprintTableId } from "./tables/P_Blueprint.sol";
import { P_MaxLevel, P_MaxLevelTableId } from "./tables/P_MaxLevel.sol";
import { P_Production, P_ProductionData, P_ProductionTableId } from "./tables/P_Production.sol";
import { P_UnitProdTypes, P_UnitProdTypesTableId } from "./tables/P_UnitProdTypes.sol";
import { P_UnitProdMultiplier, P_UnitProdMultiplierTableId } from "./tables/P_UnitProdMultiplier.sol";
import { SetItemUnitFactories, SetItemUnitFactoriesData, SetItemUnitFactoriesTableId } from "./tables/SetItemUnitFactories.sol";
import { SetUnitFactories, SetUnitFactoriesTableId } from "./tables/SetUnitFactories.sol";
import { P_ByLevelMaxResourceUpgrades, P_ByLevelMaxResourceUpgradesTableId } from "./tables/P_ByLevelMaxResourceUpgrades.sol";
import { P_ListMaxResourceUpgrades, P_ListMaxResourceUpgradesTableId } from "./tables/P_ListMaxResourceUpgrades.sol";
import { P_ConsumesResource, P_ConsumesResourceTableId } from "./tables/P_ConsumesResource.sol";
import { BuildingType, BuildingTypeTableId } from "./tables/BuildingType.sol";
import { Children, ChildrenTableId } from "./tables/Children.sol";
import { ProductionRate, ProductionRateTableId } from "./tables/ProductionRate.sol";
import { ConsumptionRate, ConsumptionRateTableId } from "./tables/ConsumptionRate.sol";
import { IsActive, IsActiveTableId } from "./tables/IsActive.sol";
