// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMessageSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMessageSystem {
  function upgradeBounty_MessageSystem_incrementMessage(string memory message) external returns (uint32);

  function upgradeBounty_MessageSystem_incrementMessageFrom(
    address delegator,
    string memory message
  ) external returns (uint32);
}
