// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "./../index.sol";

/**
 * @title IUpgrBounSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUpgrBounSystem {
  function upgradeBounty_UpgrBounSystem_depositBounty(
    PositionData memory coord
  ) external payable returns (uint256 bountyValue);

  function upgradeBounty_UpgrBounSystem_withdrawBounty(
    PositionData memory coord
  ) external returns (uint256 bountyValue);

  function upgradeBounty_UpgrBounSystem_upgradeForBounty(
    address bountyPublisher,
    PositionData memory coord
  ) external returns (bytes memory newBuildingEntity);
}
