// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { EBuilding } from "src/Types.sol";
import { PositionData } from "codegen/Tables.sol";

interface IBuildSystem {
  function build(EBuilding buildingType, PositionData memory coord) external returns (bytes32 buildingEntity);
}
