// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { EBuilding } from "codegen/Types.sol";
import { PositionData } from "codegen/Tables.sol";

interface IBuildSystem {
  function execute(EBuilding buildingType, PositionData memory coord) external returns (bytes memory);
}
