// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "codegen/Tables.sol";

interface IDestroySystem {
  function destroy(PositionData memory coord) external returns (bytes32 buildingEntity);
}
