[profile.default]
solc_version = "0.8.24"
ffi = false
fuzz_runs = 256
# optimizer = true
# optimizer_runs = 3000
verbosity = 2
src = "src"
test = "test"
out = "out"
allow_paths = [
  # pnpm symlinks to the project root's node_modules
  "../../node_modules",
  # template uses linked mud packages from within the mud monorepo
  "../../../../packages",
  # projects created from this template and using linked mud packages
  "../../../mud/packages",
]
extra_output_files = ["abi", "evm.bytecode"]
fs_permissions = [{ access = "read", path = "./" }]

[profile.caldera]
eth_rpc_url = "https://primodium-bedrock.calderachain.xyz/replica-http"
chain_id = 12523

[profile.caldera-sepolia]
eth_rpc_url = "https://primodium-sepolia.rpc.caldera.xyz/http"
chain_id = 10017

[profile.redstone-holesky]
eth_rpc_url = "https://rpc.holesky.redstone.xyz"
chain_id = 17001

[profile.base-sepolia]
eth_rpc_url = "https://sepolia.base.org"
chain_id = 84532

[profile.skale-nebula]
#eth_rpc_url = "https://testnet.skalenodes.com/v1/lanky-ill-funny-testnet"
eth_rpc_url = "https://lanky-ill-funny-testnet-indexer.skalenodes.com:10136"
chain_id = 37084624

[profile.skale-calypso]
eth_rpc_url = "https://giant-half-dual-testnet-indexer.skalenodes.com:10072"
chain_id = 974399131

[profile.skale-europa]
eth_rpc_url = "https://juicy-low-small-testnet-indexer.skalenodes.com:10008"
chain_id = 1444673419


[profile.skale-bite]
eth_rpc_url = "https://testnet-0.skalenodes.com:10008"
chain_id = 1289306510

  

