import { Animation } from "@latticexyz/phaserx/dist/types";

export const animationConfig: Animation<any>[] = [
  {
    key: "mainbase/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level1/Main_Base_LVL1_",
    suffix: ".png",
  },
  {
    key: "mainbase/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level2/Main_Base_LVL2_",
    suffix: ".png",
  },
  {
    key: "mainbase/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level3/Main_Base_LVL3_",
    suffix: ".png",
  },
  {
    key: "mainbase/level4",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level4/Main_Base_LVL4_",
    suffix: ".png",
  },
  {
    key: "mainbase/level5",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level5/Main_Base_LVL5_",
    suffix: ".png",
  },
  {
    key: "ironmine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/ironmine/level1/Miner_Iron_LVL1_",
    suffix: ".png",
  },
  {
    key: "ironmine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/ironmine/level2/Miner_Iron_LVL2_",
    suffix: ".png",
  },
  {
    key: "ironmine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/ironmine/level3/Miner_Iron_LVL3_",
    suffix: ".png",
  },
  {
    key: "coppermine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/coppermine/level1/Miner_Copper_LVL1_",
    suffix: ".png",
  },
  {
    key: "coppermine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/coppermine/level2/Miner_Copper_LVL2_",
    suffix: ".png",
  },
  {
    key: "coppermine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/coppermine/level3/Miner_Copper_LVL3_",
    suffix: ".png",
  },
  {
    key: "lithiummine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/lithiummine/Miner_Lithium_LVL1_",
    suffix: ".png",
  },
  {
    key: "sulfurmine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/sulfurmine/level1/Miner_Sulfur_LVL1_",
    suffix: ".png",
  },
  {
    key: "alloyfactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/alloy-factory/level1/Alloy_Factory",
    suffix: ".png",
  },
  {
    key: "pvcfactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 7,
    repeat: -1,
    prefix:
      "sprites/photovoltaic-cell-factory/level1/Photovoltaic_Factory_LVL1_",
    suffix: ".png",
  },
  {
    key: "pvcfactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 7,
    repeat: -1,
    prefix:
      "sprites/photovoltaic-cell-factory/level2/Photovoltaic_Factory_LVL2_",
    suffix: ".png",
  },
  {
    key: "ironplatefactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/plating-factory/level1/Plating_Factory_LVL1_",
    suffix: ".png",
  },
  {
    key: "ironplatefactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/plating-factory/level2/Plating_Factory_LVL2_",
    suffix: ".png",
  },
  {
    key: "storageunit/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/storage-facility/level3/Storage_Facility_LVL3_",
    suffix: ".png",
  },
  {
    key: "solarpanel/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 18,
    repeat: -1,
    prefix: "sprites/solar-panels/level1/Solar_Panels_LVL1_",
    suffix: ".png",
  },
  {
    key: "solarpanel/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 18,
    repeat: -1,
    prefix: "sprites/solar-panels/level2/Solar_Panels_LVL2_",
    suffix: ".png",
  },
  {
    key: "starmapperstation/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/starmapper-station/level1/Starmapper",
    suffix: ".png",
  },
  {
    key: "hangar/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/hangar/level1/Hangar",
    suffix: ".png",
  },
  {
    key: "Workshop/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/drone-factory/normal/Drone_Factory",
    suffix: ".png",
  },
];
