// Autogenerated using mud system-types
import { AttackSystem } from "./ethers-contracts/AttackSystem";
import { BuildPathSystem } from "./ethers-contracts/BuildPathSystem";
import { BuildSystem } from "./ethers-contracts/BuildSystem";
import { ClaimFromFactorySystem } from "./ethers-contracts/ClaimFromFactorySystem";
import { ClaimFromMineSystem } from "./ethers-contracts/ClaimFromMineSystem";
import { CraftSystem } from "./ethers-contracts/CraftSystem";
import { DestroyPathSystem } from "./ethers-contracts/DestroyPathSystem";
import { DestroySystem } from "./ethers-contracts/DestroySystem";
import { IncrementSystem } from "./ethers-contracts/IncrementSystem";
import { ResearchSystem } from "./ethers-contracts/ResearchSystem";
import { StarterPackSystem } from "./ethers-contracts/StarterPackSystem";
 
export type SystemTypes = {
  "system.Attack": AttackSystem;
  "system.BuildPath": BuildPathSystem;
  "system.Build": BuildSystem;
  "system.ClaimFromFactory": ClaimFromFactorySystem;
  "system.ClaimFromMine": ClaimFromMineSystem;
  "system.Craft": CraftSystem;
  "system.DestroyPath": DestroyPathSystem;
  "system.Destroy": DestroySystem;
  "system.Increment": IncrementSystem;
  "system.Research": ResearchSystem;
  "system.StarterPackSystem": StarterPackSystem;
};
