// Autogenerated using mud system-types
export const systemToId = {
  AttackSystem: "system.Attack",
  BuildPathSystem: "system.BuildPath",
  BuildSystem: "system.Build",
  ClaimFromFactorySystem: "system.ClaimFromFactory",
  ClaimFromMineSystem: "system.ClaimFromMine",
  CraftSystem: "system.Craft",
  DestroyPathSystem: "system.DestroyPath",
  DestroySystem: "system.Destroy",
  IncrementSystem: "system.Increment",
  ResearchSystem: "system.Research",
  StarterPackSystem: "system.StarterPackSystem",
};

export const idToSystem = {
  "system.Attack": "AttackSystem",
  "system.BuildPath": "BuildPathSystem",
  "system.Build": "BuildSystem",
  "system.ClaimFromFactory": "ClaimFromFactorySystem",
  "system.ClaimFromMine": "ClaimFromMineSystem",
  "system.Craft": "CraftSystem",
  "system.DestroyPath": "DestroyPathSystem",
  "system.Destroy": "DestroySystem",
  "system.Increment": "IncrementSystem",
  "system.Research": "ResearchSystem",
  "system.StarterPackSystem": "StarterPackSystem",
};
  