// Autogenerated using mud system-types
import AttackSystem from "../abi/AttackSystem.json";
import BuildPathSystem from "../abi/BuildPathSystem.json";
import BuildSystem from "../abi/BuildSystem.json";
import ClaimFromFactorySystem from "../abi/ClaimFromFactorySystem.json";
import ClaimFromMineSystem from "../abi/ClaimFromMineSystem.json";
import CraftSystem from "../abi/CraftSystem.json";
import DestroyPathSystem from "../abi/DestroyPathSystem.json";
import DestroySystem from "../abi/DestroySystem.json";
import IncrementSystem from "../abi/IncrementSystem.json";
import ResearchSystem from "../abi/ResearchSystem.json";
import StarterPackSystem from "../abi/StarterPackSystem.json";

export const SystemAbis = {
  "system.Attack": AttackSystem.abi,
  "system.BuildPath": BuildPathSystem.abi,
  "system.Build": BuildSystem.abi,
  "system.ClaimFromFactory": ClaimFromFactorySystem.abi,
  "system.ClaimFromMine": ClaimFromMineSystem.abi,
  "system.Craft": CraftSystem.abi,
  "system.DestroyPath": DestroyPathSystem.abi,
  "system.Destroy": DestroySystem.abi,
  "system.Increment": IncrementSystem.abi,
  "system.Research": ResearchSystem.abi,
  "system.StarterPackSystem": StarterPackSystem.abi,
};
