// Autogenerated using mud system-types
import BuildPathFromFactoryToMainBaseSystem from "../abi/BuildPathFromFactoryToMainBaseSystem.json";
import BuildPathFromMineToFactorySystem from "../abi/BuildPathFromMineToFactorySystem.json";
import BuildPathFromMineToMainBaseSystem from "../abi/BuildPathFromMineToMainBaseSystem.json";
import BuildPathSystem from "../abi/BuildPathSystem.json";
import BuildSystem from "../abi/BuildSystem.json";
import ClaimFromMineSystem from "../abi/ClaimFromMineSystem.json";
import ComponentDevSystem from "../abi/ComponentDevSystem.json";
import CraftSystem from "../abi/CraftSystem.json";
import DestroyPathSystem from "../abi/DestroyPathSystem.json";
import DestroySystem from "../abi/DestroySystem.json";
import IncrementSystem from "../abi/IncrementSystem.json";
import PostBuildSystem from "../abi/PostBuildSystem.json";
import PostDestroyPathSystem from "../abi/PostDestroyPathSystem.json";
import PostDestroySystem from "../abi/PostDestroySystem.json";
import PostUpgradeFactorySystem from "../abi/PostUpgradeFactorySystem.json";
import PostUpgradeMineSystem from "../abi/PostUpgradeMineSystem.json";
import ResearchSystem from "../abi/ResearchSystem.json";
import SpendRequiredResourcesSystem from "../abi/SpendRequiredResourcesSystem.json";
import UpgradeSystem from "../abi/UpgradeSystem.json";

export const SystemAbis = {
  "system.BuildPathFromFactoryToMainBase": BuildPathFromFactoryToMainBaseSystem.abi,
  "system.BuildPathFromMineToFactory": BuildPathFromMineToFactorySystem.abi,
  "system.BuildPathFromMineToMainBase": BuildPathFromMineToMainBaseSystem.abi,
  "system.BuildPath": BuildPathSystem.abi,
  "system.Build": BuildSystem.abi,
  "system.ClaimFromMine": ClaimFromMineSystem.abi,
  "system.ComponentDev": ComponentDevSystem.abi,
  "system.Craft": CraftSystem.abi,
  "system.DestroyPath": DestroyPathSystem.abi,
  "system.Destroy": DestroySystem.abi,
  "system.Increment": IncrementSystem.abi,
  "system.PostBuild": PostBuildSystem.abi,
  "system.PostDestroyPath": PostDestroyPathSystem.abi,
  "system.PostDestroy": PostDestroySystem.abi,
  "system.PostUpgradeFactory": PostUpgradeFactorySystem.abi,
  "system.PostUpgradeMine": PostUpgradeMineSystem.abi,
  "system.Research": ResearchSystem.abi,
  "system.SpendRequiredResources": SpendRequiredResourcesSystem.abi,
  "system.Upgrade": UpgradeSystem.abi,
};
