// Autogenerated using mud system-types
import AttackSystem from "../abi/AttackSystem.json";
import BuildPathSystem from "../abi/BuildPathSystem.json";
import BuildSystem from "../abi/BuildSystem.json";
import ClaimFromFactorySystem from "../abi/ClaimFromFactorySystem.json";
import ClaimFromMineSystem from "../abi/ClaimFromMineSystem.json";
import CraftSystem from "../abi/CraftSystem.json";
import DebugAcquireResourcesBasedOnRequirementSystem from "../abi/DebugAcquireResourcesBasedOnRequirementSystem.json";
import DebugAcquireResourcesSystem from "../abi/DebugAcquireResourcesSystem.json";
import DebugAcquireStorageForAllResourcesSystem from "../abi/DebugAcquireStorageForAllResourcesSystem.json";
import DebugIgnoreBuildLimitForBuildingSystem from "../abi/DebugIgnoreBuildLimitForBuildingSystem.json";
import DebugRemoveBuildingRequirementsSystem from "../abi/DebugRemoveBuildingRequirementsSystem.json";
import DebugRemoveBuildLimitSystem from "../abi/DebugRemoveBuildLimitSystem.json";
import DebugRemoveUpgradeRequirementsSystem from "../abi/DebugRemoveUpgradeRequirementsSystem.json";
import DestroyPathSystem from "../abi/DestroyPathSystem.json";
import DestroySystem from "../abi/DestroySystem.json";
import IncrementSystem from "../abi/IncrementSystem.json";
import PostUpgradeSystem from "../abi/PostUpgradeSystem.json";
import ResearchSystem from "../abi/ResearchSystem.json";
import StarterPackSystem from "../abi/StarterPackSystem.json";
import UpgradeSystem from "../abi/UpgradeSystem.json";

export const SystemAbis = {
  "system.Attack": AttackSystem.abi,
  "system.BuildPath": BuildPathSystem.abi,
  "system.Build": BuildSystem.abi,
  "system.ClaimFromFactory": ClaimFromFactorySystem.abi,
  "system.ClaimFromMine": ClaimFromMineSystem.abi,
  "system.Craft": CraftSystem.abi,
  "system.DebugAcquireResourcesBasedOnRequirement": DebugAcquireResourcesBasedOnRequirementSystem.abi,
  "system.DebugAcquireResources": DebugAcquireResourcesSystem.abi,
  "system.DebugAcquireStorageForAllResources": DebugAcquireStorageForAllResourcesSystem.abi,
  "system.DebugIgnoreBuildLimitForBuilding": DebugIgnoreBuildLimitForBuildingSystem.abi,
  "system.DebugRemoveBuildingRequirements": DebugRemoveBuildingRequirementsSystem.abi,
  "system.DebugRemoveBuildLimit": DebugRemoveBuildLimitSystem.abi,
  "system.DebugRemoveUpgradeRequirements": DebugRemoveUpgradeRequirementsSystem.abi,
  "system.DestroyPath": DestroyPathSystem.abi,
  "system.Destroy": DestroySystem.abi,
  "system.Increment": IncrementSystem.abi,
  "system.PostUpgrade": PostUpgradeSystem.abi,
  "system.Research": ResearchSystem.abi,
  "system.StarterPackSystem": StarterPackSystem.abi,
  "system.Upgrade": UpgradeSystem.abi,
};
