// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IStore } from "@latticexyz/store/src/IStore.sol";

import { MainBasePrototype } from "../Prototypes.sol";

function createPrototypes(IStore store) {
  MainBasePrototype(store);
}
