// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetClearSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetClearSystem {
  function Primodium__uncheckedAbandonFleet(bytes32 fleetEntity) external;

  function Primodium__resetFleetIfNoUnitsLeft(bytes32 fleetEntity) external;
}
