// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import { IStore } from "@latticexyz/store/src/IStore.sol";

import { P_Terrain } from "codegen/Tables.sol";
import { EResource } from "codegen/Types.sol";

function CreateTerrain(IStore store) {
  P_Terrain.set(store, 0, 8, EResource.Lithium);
  P_Terrain.set(store, 1, 8, EResource.Lithium);
  P_Terrain.set(store, 2, 8, EResource.Lithium);
  P_Terrain.set(store, 3, 8, EResource.Lithium);
  P_Terrain.set(store, 4, 8, EResource.Lithium);
  P_Terrain.set(store, 5, 8, EResource.Lithium);
  P_Terrain.set(store, 6, 8, EResource.Lithium);
  P_Terrain.set(store, 7, 8, EResource.Lithium);
  P_Terrain.set(store, 8, 8, EResource.Lithium);
  P_Terrain.set(store, 9, 8, EResource.Lithium);
  P_Terrain.set(store, 10, 8, EResource.Lithium);
  P_Terrain.set(store, 11, 8, EResource.Lithium);
  P_Terrain.set(store, 13, 8, EResource.Lithium);
  P_Terrain.set(store, 14, 8, EResource.Lithium);
  P_Terrain.set(store, 20, 8, EResource.Iron);
  P_Terrain.set(store, 21, 8, EResource.Iron);
  P_Terrain.set(store, 25, 8, EResource.Iron);
  P_Terrain.set(store, 26, 8, EResource.Iron);
  P_Terrain.set(store, 27, 8, EResource.Iron);
  P_Terrain.set(store, 28, 8, EResource.Iron);
  P_Terrain.set(store, 29, 8, EResource.Iron);
  P_Terrain.set(store, 30, 8, EResource.Iron);
  P_Terrain.set(store, 31, 8, EResource.Iron);
  P_Terrain.set(store, 32, 8, EResource.Iron);
  P_Terrain.set(store, 33, 8, EResource.Iron);
  P_Terrain.set(store, 34, 8, EResource.Iron);
  P_Terrain.set(store, 35, 8, EResource.Iron);
  P_Terrain.set(store, 36, 8, EResource.Iron);
  P_Terrain.set(store, 20, 9, EResource.Iron);
  P_Terrain.set(store, 21, 9, EResource.Iron);
  P_Terrain.set(store, 28, 9, EResource.Iron);
  P_Terrain.set(store, 32, 9, EResource.Iron);
  P_Terrain.set(store, 0, 15, EResource.Sulfur);
  P_Terrain.set(store, 1, 15, EResource.Sulfur);
  P_Terrain.set(store, 2, 15, EResource.Sulfur);
  P_Terrain.set(store, 3, 15, EResource.Sulfur);
  P_Terrain.set(store, 4, 15, EResource.Sulfur);
  P_Terrain.set(store, 5, 15, EResource.Sulfur);
  P_Terrain.set(store, 6, 15, EResource.Sulfur);
  P_Terrain.set(store, 7, 15, EResource.Sulfur);
  P_Terrain.set(store, 8, 15, EResource.Sulfur);
  P_Terrain.set(store, 9, 15, EResource.Sulfur);
  P_Terrain.set(store, 10, 15, EResource.Sulfur);
  P_Terrain.set(store, 11, 15, EResource.Sulfur);
  P_Terrain.set(store, 20, 15, EResource.Copper);
  P_Terrain.set(store, 21, 15, EResource.Copper);
  P_Terrain.set(store, 25, 15, EResource.Copper);
  P_Terrain.set(store, 26, 15, EResource.Copper);
  P_Terrain.set(store, 27, 15, EResource.Copper);
  P_Terrain.set(store, 28, 15, EResource.Copper);
  P_Terrain.set(store, 29, 15, EResource.Copper);
  P_Terrain.set(store, 30, 15, EResource.Copper);
  P_Terrain.set(store, 31, 15, EResource.Copper);
  P_Terrain.set(store, 32, 15, EResource.Copper);
  P_Terrain.set(store, 33, 15, EResource.Copper);
  P_Terrain.set(store, 34, 15, EResource.Copper);
  P_Terrain.set(store, 35, 15, EResource.Copper);
  P_Terrain.set(store, 36, 15, EResource.Copper);
  P_Terrain.set(store, 20, 16, EResource.Copper);
  P_Terrain.set(store, 28, 16, EResource.Copper);
}
